---
title: "project_draft"
author: "Amirreza Eshraghi"
date: '2023-03-02'
output: html_document
---



```{r}
#install.packages('bnlearn')
library(bnlearn)
# define a function that takes a dataframe of returns, a type of test and a fixed variable
# it returns a dataframe with p-values and correlations for every pair of stocks given the fixed variable
ci_test_pairs <- function(df, test, fixed) {
  # get the names of the columns that are not the fixed variable
  stocks <- names(df)[names(df) != fixed]
  # create an empty dataframe to store the results
  results <- data.frame()
  # loop over all pairs of stocks
  for (i in 1:(length(stocks) - 1)) {
    for (j in (i + 1):length(stocks)) {
      # get the names of the pair
      x <- stocks[i]
      y <- stocks[j]
      # perform the conditional independence test given the fixed variable
      test_result <- ci.test(x, y, fixed, data = df, test = test)
      # extract the p-value and the correlation from the test result
      p_value <- test_result$p.value
      correlation <- cor(df[[x]], df[[y]])
      # append a row to the results dataframe with the pair names, p-value and correlation
      results <- rbind(results, data.frame(x = x, y = y, p_value = p_value, correlation = correlation))
    }
  }
  # return the results dataframe
  return(results)
}
```

```{r}
df<- read.csv("C:/Users/shriy/Documents/Project_Petrovic-main/Project_Petrovic-main/returns_data.csv")

df_nodate<- df[,-1]


#different slices corresponding to federal reserve interest rates hiking/cutting/pausing

df1<- df[ df$Date> "2000-11-01"  &   df$Date < "2001-12-31",-1 ]
 
df2<- df[ df$Date> "2002-01-01"  &   df$Date < "2002-10-31",-1 ]

df3<- df[ df$Date> "2002-11-01"  &   df$Date < "2004-06-31",-1 ]

df4<- df[ df$Date> "2004-07-01"  &   df$Date < "2006-08-31",-1 ]

df5<- df[ df$Date> "2006-08-31"  &   df$Date < "2007-08-01",-1 ]

df6<- df[ df$Date> "2007-08-01"  &   df$Date < "2008-05-01",-1 ]

df7<- df[ df$Date> "2008-05-01"  &   df$Date < "2008-09-31",-1 ]

df8<- df[ df$Date> "2008-09-31"  &   df$Date < "2009-01-01",-1 ]

df9<- df[ df$Date> "2009-01-01"  &   df$Date < "2015-12-31",-1 ]

df10<- df[ df$Date> "2016-01-01"  &   df$Date < "2019-07-31",-1 ]

df11<- df[ df$Date> "2019-07-31"  &   df$Date < "2020-05-01",-1 ]

df12<- df[ df$Date> "2020-05-01"  &   df$Date < "2022-02-01",-1 ]

dff = list(df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11,df12)

results=list()

for (i in 1:12){
  res<-ci_test_pairs(df = dff[[i]],fixed="DXY")
  results[[i]]<- res
  
}

#the result of the test is available as a list, each element corresponds to a time-slice 

  

```

```{r}
df

#df <- subset(df, select = -c(Date))
#df
cor_data = cor(df)
cor_data
```

```{r}
#install.packages("tabplot", dependencies = TRUE)
require(ggplot2)
#install.packages('tabplot')
#library(tabplot)
```

#Relationship Between Numerical Variables
```{r}
#install.packages('corrgram')
library(corrgram)

#Visualizing using a Correlogram
corrgram(corr)

```

```{r}
#count_data<- read.csv("/users/amirreza/Desktop/returns_data_classified.csv")
#count_data



```


```{r}
p_value_eval<- function(x){
  if(x<0.1){
    ret=0
  }
  else{
    ret=1
    
  }
  return(ret)
}
```

```{r}
#example for "Data" format x,y,edge:

l<- lapply(results[[3]]$p_value, p_value_eval)
results[[3]]$edge<- as.integer(l)
example<- results[[3]][c("x","y","edge")]
example
```



```{r}
library(dplyr) 
library(igraph)
#filtered only the edges that contain 1
edges1 <- filter(example, edge == "1")
edges1
#plotted the graph 
g <- graph_from_data_frame(edges1, directed = FALSE)
plot(g, vertex.label = V(g)$name, edge.label = E(g)$weight)

```

